---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.13
  ansible_runner:
    package_pip: ansible-runner
  galaxy: 
    collections:
      - kubernetes.core
      - ansible.utils
  python:
    - kubernetes
    - pyyaml
    - jsonpatch
  system:
    - tar
    - gzip
    - util-linux
    # --- เอา openshift-clients ออกจากตรงนี้ ---

additional_build_steps:
  prepend_base:
    - RUN microdnf install -y python3-pip tar gzip && microdnf clean all
  
  append_final:
    # ดาวน์โหลดและติดตั้ง oc binary โดยตรงจาก Mirror ของ OpenShift
    - |
      RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | tar -xvzf - -C /usr/local/bin/ oc && \
      chmod +x /usr/local/bin/oc
    - 'RUN echo "Build completed: oc binary installed via curl"'
    - RUN ansible-galaxy collection list