---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.13
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base:
    # 1. ติดตั้ง Tools และ Dependencies สำหรับการคอมไพล์ (แก้ปัญหา Python.h และ libxml)
    - RUN microdnf install -y python3.11-pip tar gzip gcc python3.11-devel systemd-devel libxml2-devel && microdnf clean all
  
  append_final:
    # 2. ใช้ curl โหลด oc และ kubectl โดยตรง (ข้ามปัญหา No package matches 'openshift-clients')
    - |
      RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | tar -xvzf - -C /usr/local/bin/ oc kubectl && \
      chmod +x /usr/local/bin/oc /usr/local/bin/kubectl
    - 'RUN echo "Build completed: oc and kubectl installed via curl successfully"'
    - RUN ansible-galaxy collection list

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'